### ISSUE TITLE
歌单不能下载，报错

### ISSUE THREAD

**Issue by zhengyishiming** [anjia0532/netease_download#16]
PS E:\Github\netease_download> python main.py https://music.163.com/#/playlist?id=2850086850
https://music.163.com/#/playlist?id=2850086850
  -- 正在分析歌单信息 ...
post_request error
Traceback (most recent call last):
  File "E:\Github\netease_download\main.py", line 452, in <module>
    main(args.url)
  File "E:\Github\netease_download\main.py", line 434, in main
    x.url_parser(url)
  File "E:\Github\netease_download\main.py", line 398, in url_parser
    self.download_playlist(self.id_parser('playlist'))
  File "E:\Github\netease_download\main.py", line 237, in download_playlist
    songs = result['result']['tracks']
TypeError: 'NoneType' object is not subscriptable
PS E:\Github\netease_download> python main.py
usage: main.py [-h] [-d DIR] [-c] url
main.py: error: the following arguments are required: url
PS E:\Github\netease_download> python main.py https://music.163.com/song?id=66842
https://music.163.com/song?id=66842

**Comment by anjia0532** [comment]
该项目已经太久不维护了
