### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by 14SHIKE** [anjia0532/netease_download#4]
[2;92m
  -- 正在分析歌曲信息 ...[0m
post_request error
Traceback (most recent call last):
  File "main.py", line 450, in <module>
    main(args.url)
  File "main.py", line 432, in main
    x.url_parser(url)
  File "main.py", line 417, in url_parser
    self.download_song(self.id_parser('song'))
  File "main.py", line 224, in download_song
    self.get_song_infos(result['songs'])
  File "main.py", line 181, in get_song_infos
    urls=self.get_durls(songs)
  File "main.py", line 151, in get_durls
    return dict([str(s["id"]),s["url"]] for s in result['data'] if result['code'] == 200)
TypeError: 'NoneType' object is not subscriptable

**Comment by anjia0532** [comment]
url 给一下

**Comment by 14SHIKE** [comment]
刚才又试了三个链接，发现正常了
可能是我那天下了太多（2500多）用别的项目netease-cloud-music-dl也是出现了错误查到需要在config.py里面添加headers cookie 但不知道怎么做

Return {'code': -460, 'msg': 'Cheating'} when try to post {'ids': [273369], 'br': 320000, 'csrf_token': ''} => http://music.163.com/weapi/song/enhance/player/url?csrf_token=
Traceback (most recent call last):
File "E:\Python3.6.5\Scripts\ncm-script.py", line 11, in 
load_entry_point('netease-cloud-music-dl==0.2.0', 'console_scripts', 'ncm')()
File "E:\Python3.6.5\lib\site-packages\netease_cloud_music_dl-0.2.0-py3.6.egg\ncm\start.py", line 76, in main
File "E:\Python3.6.5\lib\site-packages\netease_cloud_music_dl-0.2.0-py3.6.egg\ncm\start.py", line 42, in download_playlist_songs
File "E:\Python3.6.5\lib\site-packages\netease_cloud_music_dl-0.2.0-py3.6.egg\ncm\downloader.py", line 49, in download_song_by_song
File "E:\Python3.6.5\lib\site-packages\netease_cloud_music_dl-0.2.0-py3.6.egg\ncm\api.py", line 73, in get_song_url
TypeError: 'NoneType' object is not subscriptable

**Comment by 14SHIKE** [comment]
python main.py https://music.163.com/playlist?id=874616835
python main.py https://music.163.com/playlist?id=497987290

**Comment by anjia0532** [comment]
[捂脸] 你一次性下多了，估计被当成爬虫了吧，用代理ip试试。你如果要加header，直接改main.py就行了。百度搜python requests header

**Comment by anjia0532** [comment]
https://github.com/anjia0532/netease_download/blob/master/main.py#L136
