### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by machsix** [anjia0532/netease_download#9]
python3 main.py https://music.163.com/#/album?id=34751905

运行结果
``` bash
  >> 11 首歌曲将要下载.

  ++ 正在下载: #1/11# 不害怕 - 张韶涵.mp3
  ++ mp3_quality: High
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.4/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/lib/python3.4/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.4/http/client.py", line 1137, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.4/http/client.py", line 1182, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.4/http/client.py", line 1133, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.4/http/client.py", line 963, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.4/http/client.py", line 898, in send
    self.connect()
  File "/usr/lib/python3.4/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.4/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f68d02328d0>: Failed to establish a new connection: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.4/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='m10.music.126.net', port=80): Max retries exceeded with url: /20190205085912/ce42394e7b338f149318ca69
78a52548/ymusic/9967/e28c/91f1/7cedb2d4b86386f8022faafaa245499e.mp3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d02328d0>:
 Failed to establish a new connection: [Errno 113] No route to host',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 451, in <module>
    main(args.url)
  File "main.py", line 433, in main
    x.url_parser(url)
  File "main.py", line 428, in url_parser
    self.download()
  File "main.py", line 379, in download
    r = requests.session().get(i['durl'], stream=True,headers=download_headers,timeout=self.timeout)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='m10.music.126.net', port=80): Max retries exceeded with url: /20190205085912/ce42394e7b338f149318c
a6978a52548/ymusic/9967/e28c/91f1/7cedb2d4b86386f8022faafaa245499e.mp3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d02328d
0>: Failed to establish a new connection: [Errno 113] No route to host',))
```

ping结果如下
```
[root@host netease_download]# ping m10.music.126.net
PING m10.music.126.net (113.107.57.64) 56(84) bytes of data.
From 113.107.57.1 (113.107.57.1) icmp_seq=14 Destination Host Unreachable
From 113.107.57.1 (113.107.57.1) icmp_seq=15 Destination Host Unreachable
```

所以是网络原因？我是vps在海外挂的unblock youku的dns

**Comment by anjia0532** [comment]
不好意思，刚回复。网易云音乐的很多音乐因为版权问题，不支持境外ip访问，另外根据你ping 的结果看，确实是网络问题。
